/* -------------------------------------------------------------------------
 * types/accounting.types.ts — PROVISIONAL, hand-written.
 * -------------------------------------------------------------------------
 * database.types.ts is generated by `supabase gen types typescript` against
 * the LIVE schema. The accounting migration
 * (supabase/migrations/20260905000000_accounting_ledger.sql) has NOT been
 * applied to any database, so none of the tables/enums below exist yet —
 * there is nothing for the generator to introspect.
 *
 * These types are written to match that migration file EXACTLY, field for
 * field. Once the migration is applied, run:
 *
 *   npx supabase gen types typescript --project-id vkkjatrawzpmdhfloens --schema iapp,public
 *
 * and delete this file — every accounting service should then import from
 * database.types.ts like every other service in this codebase, not from
 * here. Until then, this file is the single source of truth for the
 * *shape* the migration will produce, so a mismatch between this file and
 * the SQL is a bug in one of the two, not an acceptable drift.
 * ---------------------------------------------------------------------- */

export type FinancialTransactionType =
  | 'opening_balance'
  | 'revenue'
  | 'expense'
  | 'refund'
  | 'transfer_out'
  | 'transfer_in'
  | 'adjustment_increase'
  | 'adjustment_decrease';

export interface PaymentMethodRow {
  id: string;
  code: string;
  name_ar: string;
  name_en: string | null;
  is_active: boolean;
  sort_order: number;
}

export interface ExpenseCategoryRow {
  id: string;
  code: string;
  name_ar: string;
  name_en: string | null;
  is_active: boolean;
  sort_order: number;
}

export type AccountKind = 'cash' | 'bank' | 'other';

export interface AccountRow {
  id: string;
  clinic_id: string | null;
  code: string;
  name_ar: string;
  name_en: string | null;
  kind: AccountKind;
  currency: string;
  allow_overdraft: boolean;
  is_active: boolean;
  notes: string | null;
}

export interface FinancialTransactionRow {
  id: string;
  transaction_type: FinancialTransactionType;
  account_id: string;
  clinic_id: string | null;
  amount: number;
  currency: string;
  transaction_date: string; // date
  description: string | null;
  reason: string | null;
  metadata: Record<string, unknown> | null;
  patient_id: string | null;
  visit_id: string | null;
  service_id: string | null;
  expense_category_id: string | null;
  payment_method_id: string | null;
  receipt_no: string | null;
  related_transaction_id: string | null;
  legacy_payment_id: string | null;
  created_at: string;
  created_by: string;
}

export interface DailyClosingRow {
  id: string;
  clinic_id: string | null;
  closing_date: string; // date
  closed_at: string;
  closed_by: string;
  notes: string | null;
  created_at: string;
}

export interface AccountBalanceRow {
  account_id: string;
  clinic_id: string | null;
  name_ar: string;
  currency: string;
  current_balance: number;
}

export interface DailyFinancialSummaryRow {
  clinic_id: string | null;
  day: string; // date
  revenue: number | null;
  expenses: number | null;
  refunds: number | null;
  net: number | null;
}

export interface ClinicFinancialSummaryRow {
  clinic_id: string;
  name_ar: string;
  revenue: number | null;
  expenses: number | null;
  refunds: number | null;
}

export interface PaymentMethodSummaryRow {
  payment_method_id: string;
  name_ar: string;
  total_revenue: number;
  transaction_count: number;
}

export interface ServiceRevenueSummaryRow {
  service_id: string;
  name_ar: string;
  total_revenue: number;
  transaction_count: number;
}

/** Params/returns for the RPCs in the proposed migration — kept in one
 *  place so every service file references the same shape. */
export interface RecordPatientPaymentParams {
  p_patient_id: string;
  p_visit_id: string | null;
  p_clinic_id: string | null;
  p_service_id: string | null;
  p_account_id: string;
  p_amount: number;
  p_payment_method_id: string | null;
  p_notes: string | null;
  p_transaction_date?: string;
}
export interface RecordPatientPaymentResult {
  payment_id: string;
  transaction_id: string;
  receipt_no: string;
}

export interface CreateRevenueParams {
  p_account_id: string;
  p_clinic_id: string | null;
  p_amount: number;
  p_patient_id: string | null;
  p_visit_id: string | null;
  p_service_id: string | null;
  p_payment_method_id: string | null;
  p_description: string | null;
  p_transaction_date?: string;
}

export interface CreateExpenseParams {
  p_account_id: string;
  p_clinic_id: string | null;
  p_amount: number;
  p_expense_category_id: string | null;
  p_description: string | null;
  p_transaction_date?: string;
}

export interface CreateRefundParams {
  p_original_id: string;
  p_amount: number;
  p_reason: string;
  p_transaction_date?: string;
}

export interface CreateTransferParams {
  p_from_account: string;
  p_to_account: string;
  p_amount: number;
  p_description: string | null;
  p_transaction_date?: string;
}
export interface CreateTransferResult {
  out_id: string;
  in_id: string;
}

export interface CreateAdjustmentParams {
  p_account_id: string;
  p_direction: 'increase' | 'decrease';
  p_amount: number;
  p_reason: string;
  p_related_transaction_id?: string | null;
  p_transaction_date?: string;
}

export interface CreateOpeningBalanceParams {
  p_account_id: string;
  p_amount: number;
  p_transaction_date?: string;
}

export interface CreateDailyClosingParams {
  p_clinic_id: string | null;
  p_closing_date: string;
  p_notes?: string | null;
}
